sudo: required
services:
  - docker
  
before_install:
  - docker build -t sg20saksham/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sg20saksham/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-576409798710"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

